spring:
  application:
    name: URL Shorter
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:urlshortnerDB
    driver-class-name: org.h2.Driver
    username: sa
    password:

  cache:
    cache-names: shortUrlCache
    caffeine:
      spec: maximumSize=10000,expireAfterAccess=10m


logging:
  level:
    org.springdoc: TRACE


